### ISSUE TITLE
Unable to use the pkg2zip executable on Ubuntu 20.10 (64 bits)

### ISSUE THREAD

**Issue by Zileus** [evertonstz/pynps#24]
Hello,

I had an error while using pynps recently on Ubuntu 20.10. Could you please what I'm doing wrong with pynps? 
I have a desktop with GNU/Linux Debian and everything is fine... I can't find the reason why it failes on Ubunut...

Regards!

thank you for your help!

### Preliminary information:

**installed version :** 1.6.2  // through "pip3 install pynps" (updates frequently made)

**pkg2zip installation** : /home/$USER/.config/pyNPS/lib/ and make it executable by runing:

- ~/.local.bin/pkg2zip (64 bits - chmod'ed to be executable)
OR
- ~.config/pyNPS/lib/pkg2zip (64 bits - chmod'ed to be executable)

**Desktop:**  Linux HP 5.8.0-29-generic #31-Ubuntu SMP Fri Nov 6 12:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
**Command used** : pynps -c psv -GDC -r eur <xxxxx>
**Command Steps**: 
- Finding the expected game : **OK**
- Downloading or Resuming downlaod : **OK**
- Extracting through pkg2zip : **KO**

**Command output** :
PKG2ZIP] Attempting to extract [PCSBxxxxxx] xxxxxxxxx
Traceback (most recent call last):
  File "/home/<me>/.local/bin/pynps", line 8, in <module>
    sys.exit(cli_main())
  File "/home/<me>/.local/lib/python3.8/site-packages/pynps/cli/cli.py", line 662, in cli_main
    delete = run_pkg2zip(dl_dile_loc, dl_location, PKG2ZIP, pkg2zip_args, extraction_folder, i, zrif)
  File "/home/<me>/.local/lib/python3.8/site-packages/pynps/functions/functions.py", line 699, in run_pkg2zip
    process = runner(run_lst, cwd=output_location)
  File "/home/<me>/.local/lib/python3.8/site-packages/pynps/functions/functions.py", line 636, in runner
    p = subprocess.Popen(list, cwd=cwd,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/<me>/.local/bin/pkg2zip'

**Comment by evertonstz** [comment]
Hi, sorry for taking so long to answer, I was finishing my undergraduate thesis so all my projects where on hold for some months.

That's indeed a strange error. Can you try running pkg2zip in your terminal to see if it works fine?

**Comment by Zileus** [comment]
How dumb and lazy am I sometimes....!!!!
well the easiest way to solve my problem, was to compile pkg2zip binary from the sources!
The binary is found was compiled for Windows. 

Now everything is fine! Thanks for your answer even if it took months. Sometimes, priorities change...
